from __future__ import annotations

from typing import List, Optional

from fastapi import APIRouter, HTTPException

from .. import db
from ..services.extract import extract_action_items, extract_action_items_llm
from ..schemas import (
    ActionItemOut,
    ExtractActionItemsRequest,
    ExtractActionItemsResponse,
    MarkDoneRequest,
    MarkDoneResponse,
)


router = APIRouter(prefix="/action-items", tags=["action-items"])


@router.post("/extract", response_model=ExtractActionItemsResponse)
def extract(payload: ExtractActionItemsRequest) -> ExtractActionItemsResponse:
    text = payload.text.strip()
    try:
        note_id: Optional[int] = None
        if payload.save_note:
            note_id = db.insert_note(text)

        items = extract_action_items(text)
        ids = db.insert_action_items(items, note_id=note_id)
    except db.DatabaseError:
        raise HTTPException(status_code=500, detail="database error")

    return ExtractActionItemsResponse(
        note_id=note_id,
        items=[{"id": i, "text": t} for i, t in zip(ids, items)],
    )


@router.post("/extract-llm", response_model=ExtractActionItemsResponse)
def extract_llm(payload: ExtractActionItemsRequest) -> ExtractActionItemsResponse:
    # Generated by AI assistant: LLM-backed extraction endpoint
    text = payload.text.strip()
    try:
        note_id: Optional[int] = None
        if payload.save_note:
            note_id = db.insert_note(text)

        items = extract_action_items_llm(text)
        ids = db.insert_action_items(items, note_id=note_id)
    except db.DatabaseError:
        raise HTTPException(status_code=500, detail="database error")

    return ExtractActionItemsResponse(
        note_id=note_id,
        items=[{"id": i, "text": t} for i, t in zip(ids, items)],
    )


@router.get("", response_model=List[ActionItemOut])
def list_all(note_id: Optional[int] = None) -> List[ActionItemOut]:
    try:
        rows = db.list_action_items(note_id=note_id)
    except db.DatabaseError:
        raise HTTPException(status_code=500, detail="database error")
    return [
        ActionItemOut(
            id=r["id"],
            note_id=r["note_id"],
            text=r["text"],
            done=bool(r["done"]),
            created_at=r["created_at"],
        )
        for r in rows
    ]


@router.post("/{action_item_id}/done", response_model=MarkDoneResponse)
def mark_done(action_item_id: int, payload: MarkDoneRequest) -> MarkDoneResponse:
    try:
        db.mark_action_item_done(action_item_id, payload.done)
    except db.NotFoundError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except db.DatabaseError:
        raise HTTPException(status_code=500, detail="database error")
    return MarkDoneResponse(id=action_item_id, done=payload.done)


