from __future__ import annotations

from typing import List

from fastapi import APIRouter, HTTPException, status

from .. import db
from ..schemas import NoteCreate, NoteOut


router = APIRouter(prefix="/notes", tags=["notes"])


@router.post("", response_model=NoteOut, status_code=status.HTTP_201_CREATED)
def create_note(payload: NoteCreate) -> NoteOut:
    try:
        note_id = db.insert_note(payload.content.strip())
        note = db.require_note(note_id)
    except db.DatabaseError:
        raise HTTPException(status_code=500, detail="database error")
    return NoteOut(id=note["id"], content=note["content"], created_at=note["created_at"])


@router.get("", response_model=List[NoteOut])
def list_all_notes() -> List[NoteOut]:
    # Generated by AI assistant: list all notes endpoint
    try:
        rows = db.list_notes()
    except db.DatabaseError:
        raise HTTPException(status_code=500, detail="database error")
    return [NoteOut(id=r["id"], content=r["content"], created_at=r["created_at"]) for r in rows]


@router.get("/{note_id}", response_model=NoteOut)
def get_single_note(note_id: int) -> NoteOut:
    try:
        row = db.require_note(note_id)
    except db.NotFoundError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except db.DatabaseError:
        raise HTTPException(status_code=500, detail="database error")
    return NoteOut(id=row["id"], content=row["content"], created_at=row["created_at"])


