from __future__ import annotations

# Generated by AI assistant: GitHub API wrapper for MCP tools

import os
import time
from dataclasses import dataclass
from typing import Any, Dict, List, Optional

import httpx


DEFAULT_TIMEOUT_S = 15.0
GITHUB_API_BASE = "https://api.github.com"


@dataclass(frozen=True)
class RateLimitInfo:
    remaining: Optional[int] = None
    reset_epoch_seconds: Optional[int] = None

    @property
    def reset_in_seconds(self) -> Optional[int]:
        if self.reset_epoch_seconds is None:
            return None
        return max(0, int(self.reset_epoch_seconds - time.time()))


class GitHubAPIError(RuntimeError):
    pass


class GitHubRateLimitError(GitHubAPIError):
    def __init__(self, message: str, *, info: RateLimitInfo):
        super().__init__(message)
        self.info = info


def _auth_headers() -> Dict[str, str]:
    token = os.getenv("GITHUB_TOKEN", "").strip()
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": "week3-mcp-server",
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"
    return headers


def _rate_limit_info(resp: httpx.Response) -> RateLimitInfo:
    remaining: Optional[int]
    reset: Optional[int]
    try:
        remaining = int(resp.headers.get("x-ratelimit-remaining"))  # type: ignore[arg-type]
    except Exception:
        remaining = None
    try:
        reset = int(resp.headers.get("x-ratelimit-reset"))  # type: ignore[arg-type]
    except Exception:
        reset = None
    return RateLimitInfo(remaining=remaining, reset_epoch_seconds=reset)


async def _get_json(path: str, params: Dict[str, Any]) -> Any:
    url = f"{GITHUB_API_BASE}{path}"
    async with httpx.AsyncClient(timeout=DEFAULT_TIMEOUT_S, headers=_auth_headers()) as client:
        try:
            resp = await client.get(url, params=params)
        except httpx.TimeoutException as e:
            raise GitHubAPIError("GitHub request timed out") from e
        except httpx.HTTPError as e:
            raise GitHubAPIError("GitHub request failed") from e

    info = _rate_limit_info(resp)
    if resp.status_code == 403 and info.remaining == 0:
        reset_in = info.reset_in_seconds
        hint = f" (try again in ~{reset_in}s)" if reset_in is not None else ""
        raise GitHubRateLimitError(f"GitHub rate limit exceeded{hint}", info=info)

    if resp.status_code >= 400:
        try:
            payload = resp.json()
            msg = payload.get("message") if isinstance(payload, dict) else None
        except Exception:
            msg = None
        raise GitHubAPIError(msg or f"GitHub API error (HTTP {resp.status_code})")

    try:
        return resp.json()
    except Exception as e:
        raise GitHubAPIError("GitHub response was not valid JSON") from e


async def search_repositories(
    query: str,
    *,
    sort: str = "stars",
    order: str = "desc",
    per_page: int = 5,
) -> List[Dict[str, Any]]:
    """
    Search public GitHub repositories.

    Returns a list of simplified repository objects.
    """
    q = query.strip()
    if not q:
        return []
    per_page = max(1, min(int(per_page), 20))

    data = await _get_json(
        "/search/repositories",
        params={"q": q, "sort": sort, "order": order, "per_page": per_page},
    )
    items = data.get("items", []) if isinstance(data, dict) else []
    results: List[Dict[str, Any]] = []
    for r in items:
        if not isinstance(r, dict):
            continue
        results.append(
            {
                "full_name": r.get("full_name"),
                "html_url": r.get("html_url"),
                "description": r.get("description"),
                "stargazers_count": r.get("stargazers_count"),
                "language": r.get("language"),
                "updated_at": r.get("updated_at"),
            }
        )
    return results


async def list_issues(
    owner: str,
    repo: str,
    *,
    state: str = "open",
    per_page: int = 10,
) -> List[Dict[str, Any]]:
    """
    List issues for a GitHub repository.

    Note: GitHub's issues endpoint includes PRs; we filter out items with `pull_request`.
    """
    owner = owner.strip()
    repo = repo.strip()
    if not owner or not repo:
        return []
    per_page = max(1, min(int(per_page), 50))

    data = await _get_json(
        f"/repos/{owner}/{repo}/issues",
        params={"state": state, "per_page": per_page},
    )
    if not isinstance(data, list):
        return []

    results: List[Dict[str, Any]] = []
    for it in data:
        if not isinstance(it, dict):
            continue
        if "pull_request" in it:
            continue
        results.append(
            {
                "number": it.get("number"),
                "title": it.get("title"),
                "state": it.get("state"),
                "html_url": it.get("html_url"),
                "created_at": it.get("created_at"),
                "updated_at": it.get("updated_at"),
                "user": (it.get("user") or {}).get("login") if isinstance(it.get("user"), dict) else None,
            }
        )
    return results

